# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DiaryAppP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'JBDatePicker'
  pod 'RealmSwift'

  # Pods for DiaryAppP

  target 'DiaryAppPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DiaryAppPUITests' do
    # Pods for testing
  end

end
